# ExampleMod tag to use as Blowdryer settings version. Leave empty to disable.
gtnh.settings.blowdryerTag = 0.2.2
gtnh.modules.gitVersion = false

# Mod identity
modName = Better Biome Blend
modId = betterbiomeblend
modGroup = fionathemortal.betterbiomeblend
modVersion = 1.7.10-1.0.0-forge
useModGroupForPublishing = true

# Build script updates
autoUpdateBuildScript = false

# Minecraft / Forge target
minecraftVersion = 1.7.10
forgeVersion = 10.13.4.1614
channel = stable
mappingsVersion = 12
remoteMappings = https\://raw.githubusercontent.com/MinecraftForge/FML/1.7.10/conf/

# Run configuration
developmentEnvironmentUserName = Developer

# Java
enableModernJavaSyntax = false
enableGenericInjection = true

# Generated tokens
generateGradleTokenClass = fionathemortal.betterbiomeblend.Tags
gradleTokenVersion = VERSION
replaceGradleTokenInFile =

# Optional API package
apiPackage =

# Access transformers
accessTransformersFile = betterbiomeblend_at.cfg

# Mixins / coremod
usesMixins = true
separateMixinSourceSet =
usesMixinDebug = true
mixinPlugin =
mixinsPackage = mixin
coreModClass = core.CoreMod
containsMixinsAndOrCoreModOnly = false
forceEnableMixins = false

# Dependencies / repositories
usesShadowedDependencies = true
minimizeShadowedDependencies = true
relocateShadowedDependencies = true
includeWellKnownRepositories = true
excludeWellKnownRepositories =

# Publishing
usesMavenPublishing = false
modrinthProjectId =
modrinthRelations =
curseForgeProjectId =
curseForgeRelations =

# Non-GTNH properties
org.gradle.configuration-cache = true
org.gradle.parallel = true
org.gradle.jvmargs = -Xmx3G
