# Important Notes:
# Every field you add must be added to the root build.gradle expandProps map.

# Project
version=1.4.0
group=fionathemortal.betterbiomeblend
java_version=21

# Common
minecraft_version=1.21.11
mod_name=Better Biome Blend
mod_author=FionaTheMortal
mod_id=betterbiomeblend
license=LGPL
credits=
description=This mod increases the biome color blending radius and replaces the original blending algorithm with a more efficient one.
minecraft_version_range=[1.21.11, 1.22)
## This is the version of minecraft that the 'common' project uses, you can find a list of all versions here
## https://projects.neoforged.net/neoforged/neoform
neo_form_version=1.21.11-20251209.172050
# The version of ParchmentMC that is used, see https://parchmentmc.org/docs/getting-started#choose-a-version for new versions
parchment_minecraft=1.21.10
parchment_version=2025.10.12

# Fabric
fabric_version=0.141.3+1.21.11
fabric_loader_version=0.19.1

# Forge, see https://files.minecraftforge.net/net/minecraftforge/forge/ for new versions
forge_version=61.0.1
forge_loader_version_range=[61,)


# NeoForge
neoforge_version=21.11.3-beta
neoforge_loader_version_range=[4,)

# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
