# Gradle Properties
org.gradle.jvmargs = -Xmx3G

# Source Options
use_modern_java_syntax = false
use_jetbrains_annotations = false

# Compilation Options
generate_sources_jar = true
generate_javadocs_jar = false

# Testing
enable_junit_testing = false
show_testing_output = false

# Mod Information
mod_version = 1.12.2-1.2.0-forge
root_package = fionathemortal.betterbiomeblend
mod_id = betterbiomeblend
mod_name = Better Biome Blend

# Mod Metadata
mod_description = This mod increases the biome color blending radius and replaces the original blending algorithm with a more efficient one.
mod_url = https://github.com/FionaTheMortal/better-biome-blend
mod_update_json =
mod_authors = FionaTheMortal
mod_credits =
mod_logo_path =

# Mapping Properties
mapping_channel = snapshot
mapping_version = 20180814
use_dependency_at_files = true

# Run Configurations
minecraft_username = Developer
extra_jvm_args =
extra_tweak_classes =

# Publishing
publish_to_maven = false
publish_to_local_maven = false
maven_name = ${mod_name}
maven_url =
release_type = release
publish_with_changelog = false
publish_to_curseforge = false
curseforge_project_id =
curseforge_debug = false
publish_to_modrinth = false
modrinth_project_id =
modrinth_sync_readme = false
modrinth_debug = false

# Minecraft Sources
change_minecraft_sources = false

# Tags
use_tags = true
tag_class_name = ${root_package}.Tags

# Access Transformers
use_access_transformer = true
access_transformer_locations = ${mod_id}_at.cfg

# Mixins
use_mixins = true
mixin_version = 0.8.5
generate_mixins_json = false
mixin_configs = ${mod_id} ${mod_id}.optifine
mixin_refmap = refmap.${mod_id}.json
mixin_package = ${root_package}.mixin

# Coremods
is_coremod = true
coremod_includes_mod = true
coremod_plugin_class_name = ${root_package}.core.CoreMod

# AssetMover
use_asset_mover = false
asset_mover_version = 2.5
